### PR TITLE
chore: add update script

### PR DESCRIPTION
**Pull request by jeswr**
This adds a daily cron-job to check for updates to _non npm_ dependencies (i.e. emsdk, swipl, zlib & gmp) and opens a PR if there are any updates.

### CODE REVIEW

**Comment by jeswr** [comment]
@rla can you add a GH_TOKEN with write access to make this worflow run properly.

@JanWielemaker - I would be able to do this myself if this repo was moved to the `swipl-devel` org and I was added as a maintainer as @rla has previously suggested.

**Comment by rla** [comment]
"Add GH_TOKEN" - I think you would have to be a bit more specific with me :) I have no idea what those tokens are and where to get one. And where should I add it.

Moving the repo would make lots of sense. I also think that GH would add redirect (at least temp) if repo is moved so anything linking here would redirect to correct repo.

@JanWielemaker, you can add both of us as maintainers. While I'm not actively developing it, I'm still around to discuss PRs, merge them, and update documentation.

**Comment by JanWielemaker** [comment]
I'm happy to move this to SWI-Prolog/npm-swipl-wasm.  Not sure I can do this (do I have enough rights over this repo?).  I guess this will break the configured workflows?    Let me know you are prepared to handle that and I'll give it a try.

**Comment by rla** [comment]
That's quite valid question. From my side there are no external workflows. I updated and published manually. @jeswr, do you know what happens to current PRs if we move?

**Comment by jeswr** [comment]
@rla If you transfer the repo using the GitHub settings then all current branches, PRS etc should be kept as is

**Comment by jeswr** [comment]
> I guess this will break the configured workflows? Let me know you are prepared to handle that and I'll give it a try.

Only thing will be to add any missing environment variables for the actions. Everything else should be fine with the current GitHub workflow setup

**Comment by jeswr** [comment]
> I updated and published manually

Do you want me to add my standard semantic-release action after the move?

**Comment by jeswr** [comment]
> GH_TOKEN

I can do this myself if the repo is transferred. Generally speaking you generate the a PAT at https://github.com/settings/personal-access-tokens/new and then add it as a repository secret named `GH_TOKEN` at https://github.com/eyereasoner/eye-js/settings/secrets/actions.

**Comment by JanWielemaker** [comment]
It seems I cannot get into the settings of this repo to transfer it.    Guess @rla must grant me some more rights.

**Comment by jeswr** [comment]
The easiest flow (at least what I have done in the past) is that @JanWielemaker  gives @rla member access to the swipl-devel organisation and then @rla transfers the repo.

**Comment by JanWielemaker** [comment]
Ok.  Invited @rla.

**Comment by jeswr** [comment]
I'm guessing you corrected for my typo above (I meant [swipl-prolog](https://github.com/SWI-Prolog) organization not swipl-devel organisation).

**Comment by JanWielemaker** [comment]
Of course :smile:

**Comment by rla** [comment]
I tried to transfer the repository but I was not successful:

Screenshot 2023-02-19 at 12 51 42

I also tried to work around the permission issue by transferring to @JanWielemaker first but he already has a fork:

Screenshot 2023-02-19 at 12 58 27

So either @JanWielemaker has to delete his fork so I could transfer through him or he has to up my permissions temporarily on SWI-Prolog so I could transfer directly.

**Comment by JanWielemaker** [comment]
I changed the permissions on SWI-Prolog.  Hope it helps.

**Comment by JanWielemaker** [comment]
Thanks.  So that works and it seems @jeswr already did some work.

**Comment by rla** [comment]
Yeah, looks like transfer is now complete. Issues and PRs and under the new location :)

**Comment by jeswr** [comment]
> Thanks. So that works and it seems @jeswr already did some work.

not quite sure what you mean by this - haven't done any work here in the last few hrs ...

@JanWielemaker @rla could I get admin permissions for this repo (to add stricter branch protection settings and add workflow tokens). Maintainer permissions _might_ be enough - I'm not quite sure what settings they can / cannot edit.

**Comment by JanWielemaker** [comment]
> not quite sure what you mean by this - haven't done any work here in the last few hrs ...

Apparently pending stuff migrated with the repo.  Never mind.

Gave you admin rights.    Success.

**Pull request merged**
