### PR TITLE
fix: update swipl version (resolves https://github.com/rla/npm-swipl-wasm/issues/9)

### PR DESCRIPTION
**Pull request by jeswr**
Closes https://github.com/rla/npm-swipl-wasm/issues/9

### CODE REVIEW

**Comment by jeswr** [comment]
Hmm looks like the build step of this is actually erroring out when trying to run this locally with 

```
FAILED: src/wasm-preload/boot.prc 
cd /swipl-devel/build.wasm/src && /usr/bin/cmake -E make_directory /swipl-devel/build.wasm/src/wasm-preload && /usr/bin/cmake -E copy /swipl-devel/build.wasm/home/boot.prc /swipl-devel/build.wasm/src/wasm-preload/boot.prc && /usr/bin/cmake -E copy_directory /swipl-devel/build.wasm/home/library /swipl-devel/build.wasm/src/wasm-preload/library
Error copying directory from "/swipl-devel/build.wasm/home/library" to "/swipl-devel/build.wasm/src/wasm-preload/library".
[560/568] QLF compiling prolog_xref.qlf
[561/568] -- CHR bootstrap compilation step 1
ninja: build stopped: subcommand failed.
The command '/bin/sh -c /build-swipl.sh' returned a non-zero code: 1
ERROR: "build:wasm-docker:build" exited with 1.
ERROR: "build:wasm-docker" exited with 1.
```

**Comment by rla** [comment]
I'm reopening since I have not merged this PR yet. I think there is something else wrong with prolog.js but it takes some time to figure it out.

**Comment by jeswr** [comment]
I'd originally closed this because the commit this changes it to no longer corresponds to the latest commit nor the commit of any releases.

Would you like me to open up a PR that automates bumping the commit (to the commit of the latest release) with a script similar to https://github.com/eyereasoner/eye-js/blob/main/.github/workflows/update-eye.yml

**Comment by rla** [comment]
Updated in #298ffd76803a8a8cd59c81abf07ad19435723d81

**Pull request closed without merging**
