### PR TITLE
chore: upgrade deps and add CI/CD checks

### PR DESCRIPTION
**Pull request by jeswr**
This adds my standard workflows for:
 - Dependabot (including automerge if the change causes passing CI/CD checks)
 - NodeJS checks for v16, 18, 19
 - CodeQL analysis
 
Importantly this will allow us to check if the actions have all the docker support required for the build step (as discussed in https://github.com/rla/npm-swipl-wasm/issues/12#issuecomment-1407787477). If it does and this works then we can look into getting the full functionality suggested in #12 .

If these changes are accepted I would strongly reccomend enabling:
 - Automerge in your settings
 - Automated branch deletion on merge
 - Branch protection to only allow merges to main when branches are up-to-date and passing all NodeJS CI + codeQL checks.

### CODE REVIEW

**Comment by jeswr** [comment]
Setting as draft until these CI checks pass https://github.com/jeswr/npm-swipl-wasm/tree/chore/workflows (though we can see that docker *is* working.

**Comment by jeswr** [comment]
This is ready for review @rla - and will follow up with a PR including this script (https://github.com/rla/npm-swipl-wasm/compare/master...jeswr:npm-swipl-wasm:chore/auto-update-swipl#diff-b2e1e653331b913d8efb2d281bf0a06c21a1c5c34e37bac433d54daceb555fdf) once it is merged.

**Comment by rla** [comment]
CI tests are very nice, thanks a lot for them, but I'm not sure about auto-updating npm dependencies. If this is going to be too spammy I will take dep updates down.

**Comment by rla** [comment]
What does CodeQL action do? Does it run anything at all or just sets up CodeQL?

**Comment by jeswr** [comment]
> I'm not sure about auto-updating npm dependencies. If this is going to be too spammy I will take dep updates down.

:+1:  A first course of action if it is too spammy for you would just be to reduce the frequency of updates (e.g. fortnightly). You should also not need to action anything unless an updates causes CI failure in the PR due to breaking changes.

> What does CodeQL action do? Does it run anything at all or just sets up CodeQL?

It does static analysis of the code on each pull request and also as a weekly cron job. You will be sent an email notification if there are any vulnerabilities in the code in this repository (e.g. regex susceptible to DDOS attacks) and it will also be visible to maintainers under the security tab in the repo.

The cron job is there because CodeQL will add to the set of vulnerabilities it checks as new types of vulns are found (e.g. a new pattern for regex attacks); so these can be discovered even if there is limited activity on the repo for a period of time.

**Comment by rla** [comment]
@jeswr

> With the automerge in place - you should also not need to action anything unless an update causes CI failure in the PR due to breaking changes.

How to enable automerge? Currently it creates PR-s and awaits manual action. This creates huge number of emails, like 20 per day. Manually merging sends further 2 emails per PR, and starts re-checking other PR-s which feels really inefficient. Is there and option to check once per week and condense all dep updates to single PR?

**Comment by jeswr** [comment]
> How to enable automerge?

1. Go to https://github.com/rla/npm-swipl-wasm/settings and enable the following 
image.
2. Go to https://github.com/rla/npm-swipl-wasm/settings/branches add a rule for the master branch
image which requires the following status checks before merging
image

**Comment by jeswr** [comment]
>  Is there and option to check once per week and condense all dep updates to single PR?

Frustratingly dependabot does *not* support this

**Comment by jeswr** [comment]
> This creates huge number of emails, like 20 per day.

Personally I don't have github sending me emails and just look at the [github notifications](https://github.com/notifications) which hides a lot of this churn when automerge is enabled.

**Comment by rla** [comment]
@jeswr, thanks a lot! I added these settings. I also sent collab invite. Since you work actively on/with swipl, then you can now get PRs or just changes into the codebase much faster.

**Comment by rla** [comment]
@jeswr also please go over the current open PRs and merge them as you see fit. If you need some feedback on changes then I cannot help much since I'm not actively working on emscripten. Most open issues seem to stem from it. My knowledge is limited to quick search through manual/code.

**Comment by jeswr** [comment]
> I added these settings.

@rla I suspect the branch protection ones may be incorrect as I expect to see a "required" tag next to the CI checks like this:

image

It is probably the reason that the dependabot PRs are currently not automerging

>  also sent collab invite.

Thanks - I'll work through the open PRs in the coming days.

**Comment by rla** [comment]
@jeswr, can you change those settings yourself? From GH interface I cannot really see what requires special permissions and what not

**Comment by jeswr** [comment]
> @jeswr, can you change those settings yourself?

@rla Happily, but I  don't actually have permissions to do that (I believe only admins and _possibly_ maintainers are able to modify those settings)

**Comment by rla** [comment]
I think the issue might have been not having any items in "Required list". Today I managed to add CodeQL under it. Adding tests there seems to be impossible tho.

branches

Otherwise "Auto-merge" is also enabled:

auto-merge

Public user repo seems to have very limited permission management system. There is no role option in collaboration list:

collaborators

Should we transfer repo to SWI-Prolog org? @JanWielemaker

**Comment by jeswr** [comment]
No items in the required list was indeed the issue - automerge should be working. I would try and add the nodeJS checks - they should be named "Node.js CI (16.x)", "Node.js CI (18.x)", "Node.js CI (19.x)" and should appear if you just type "n" in the search field. Otherwise the merge can happen if these checks are failing.

**Pull request merged**
